[project]
name = "mcp-code-analyzer"
version = "0.1.0"
description = "MCP server for code analysis"
requires-python = ">=3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
    "venv/*",
    "__pycache__",
    "*.pyc"
]